### PR TITLE
Test on io.js

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by robwierzbowski** [comment]
Can you explain why we should be testing on iojs? What are the benefits,
will it add any workload to the maintainers?

On Friday, February 6, 2015, Mathias Bynens <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/sindresorhus/gulp-ruby-sass/pull/198
> Commit Summary
>
>    - Test on io.js
>
> File Changes
>
>    - *M* .travis.yml
>    <https://github.com/sindresorhus/gulp-ruby-sass/pull/198/files#diff-0>
>    (1)
>
> Patch Links:
>
>    - https://github.com/sindresorhus/gulp-ruby-sass/pull/198.patch
>    - https://github.com/sindresorhus/gulp-ruby-sass/pull/198.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/pull/198>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by mathiasbynens** [comment]
> Can you explain why we should be testing on iojs?

If gulp-ruby-sass fails on io.js but not on Node.js that’s probably something you’d want to know about. io.js is supposed to be compatible with Node.js, but you never know. (E.g. native modules are broken on io.js atm.)

**Comment by sindresorhus** [comment]
Hopefully in the future we'll just need to test with `iojs` ;)

**Comment by robwierzbowski** [comment]
Nice, thanks. I hadn't payed much attention to iojs until today. Looks amazing, time to migrate everything

**Pull request merged**
