### PR TITLE
Gulp source adapter, release 1.0

### PR DESCRIPTION
**Pull request by robwierzbowski**
1.0 will implement the plugin as a vinyl stream source, similar to a [vinyl adapter](https://medium.com/@eschoff/gulp-3828e8126466), but only implementing the `src` part, and using `gulp.watch` and `gulp.dest` for the rest. 

Interface: 

```js
gulp.task('styles', function () {
  return rubySass(
    // This replaces `update` or `file:file` as the source. 
    // The appropriate Sass command is fired 
    // based on whether a file or directory is passed.
    'app/styles', {
        sourcemap: true,
        style: 'expanded',
        precision: 10
    })
    .pipe($.autoprefixer(['last 2 versions']))
    .pipe(gulp.dest('.tmp/styles'))
    .pipe($.size({title: 'styles'}));
});
```

Because it's basically spawn that pipes into a gulp stream I think the only things we'd have to touch in  the output would be sourcemaps (of course) and maybe error handling.

We would lose the ability to add the plugin at any point in the pipe. But aside from linting, which could be a separate task, I've seen no common reason to transform the Sass files before compiling them to CSS. The maintenance / allowing 90% of users to use Sass like they would on the cli or with Grunt outweighs supporting those edge cases.

- [x] Implement as vinyl stream source with `update` 
- [x] Decide on error handling, re-implement logging
- [x] Add gulp-sourcemap support for `inline` and `none`
- [x]  Implement as vinyl stream source with `update` directory compilation
- [x] Add single file compilation
- [x] Add gulp-sourcemap support for `file`
- [x] Add gulp-sourcemap tests
- [x] Add gulp-sourcemap recipes
- [x] <del>Allow parallel calls to the plugin without jumble of CSS files</del> Instead of making this automatic I expanded documentation of the container option, added a recipe.
- [x] Update readme with changes

Feature level releases after 1.0 (or if I have time during the alpha)

- [ ] Support file globbing
- [ ] Add smart `src` property that delegates between dirs, files, and file globs 
- [ ] Document a working incremental build recipe

### CODE REVIEW

**Comment by xmlking** [comment]
I am switching from gulp-ruby-sass `0.7.1 -> 1.0.0-alpha` , gulp-autoprefixer `1.0.1->2.0.0`,
gulp-sourcemaps `1.3.0` and having following issues and looking for solution.
 
1. Error when set `sourcemapPath: '.'`  in 1.0.0-alpha recipe.
2. Where should I add `sourcemaps.init()` in 1.0.0-alpha recipe?
3. `watch` task was only compiling changed files before, but with  1.0.0-alpha recipe all sass files are compiled even a singe sass file is changed. 

```
Environment  : Windows 
gem -v           : 2.0.15
ruby -v           : ruby 2.0.0p481 (2014-05-08) [x64-mingw32]
sass -v           : Sass 3.4.9 (Selective Steve)
node -v          : v0.10.28
gulp -v           : 3.8.7
```
```js
import {ErrorHandler} from './errors';

let sass        = require('gulp-ruby-sass'),
  sourcemaps  = require('gulp-sourcemaps'),
  filter      = require('gulp-grep-stream'),
  browserSync = require('browser-sync'),
  autoprefixer= require('gulp-autoprefixer'),
  reload      = browserSync.reload;

export default function styles(gulp, cfg, args) {
  'use strict';
  gulp.task('styles_0.7.1"', () => {
    return gulp.src(cfg.paths.sass)
      .pipe(sourcemaps.init())
      .pipe(sass({
        style: 'expanded',
        precision: 10,
        sourcemap: (!optimize),
        sourcemapPath: '.',
        loadPath: ['bower_components/bourbon/dist', 'bower_components/compass-mixins/lib']
      }))
      .on('error', ErrorHandler.onError)
      .pipe(autoprefixer(cfg.autoprefixer))
      .pipe(sourcemaps.write('.'))
      .pipe(gulp.dest('.tmp'))
      .pipe(filter('**/*.css'))
      .pipe(reload({stream: true}));
  });

  gulp.task('styles', () => {
    return sass('app', {
      style: 'expanded',
      precision: 10,
      sourcemap: (!optimize),
      // sourcemapPath: '.',  <-- error when set with 1.0.0-alpha
      loadPath: ['bower_components/bourbon/dist', 'bower_components/compass-mixins/lib']
    })
    .on('error', ErrorHandler.onError)
    .pipe(autoprefixer(cfg.autoprefixer))
    .pipe(sourcemaps.write('.', {
      includeContent: false,
      sourceRoot: '.'
    }))
    .pipe(gulp.dest('.tmp'))
    .pipe(filter('**/*.css'))
    .pipe(reload({stream: true}));
  });
}

```

```js
export default function watch(gulp, cfg, env) {
  'use strict';
  gulp.task('watch', ['styles', 'scripts'], function () {
    gulp.watch('app/**/*.scss', ['styles']);
    gulp.watch(cfg.paths.scripts, ['transpile']);
    gulp.watch(cfg.paths.images, ['images']);
    gulp.watch('bower.json', ['wiredep']);
  });
}
```

**Comment by robwierzbowski** [comment]
Answered the other place you posted the question, here: https://github.com/sindresorhus/gulp-autoprefixer/issues/20#issuecomment-68605521.

**Comment by xmlking** [comment]
Oops! I deleted my post from other place(posted at wrong place) and re-posted here . [Concurrent update :( ]

 I still have following problem:
1. what should I change to my recipe to produce expected `index.css.map` below?
2. `browserSync.reload` also seems not working. 

__produced index.css.map__
```
{"version":3,"sources":["index.css","../../../C:/Work/mypoc/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_normalize.scss","../../../C:/Work/mypoc/bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_print.scss", .......... ;E9EirPtB","file":"index.css","sourceRoot":"."}
```
__expected index.css.map__
```
{"version":3,"sources":["index.css","../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_normalize.scss","../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/_print.scss", .......... ;E9EirPtB","file":"index.css","sourceRoot":"."}
```

**Comment by sindresorhus** [comment]
@robwierzbowski How is it coming along? Anything I can help with?

**Comment by robwierzbowski** [comment]
I think we're looking pretty good after that last issue fix. I'm going to update the Readme with gotchas, take a look at error logging with plumber, and then we can review and release a pretty well working plugin. No globbing, no incremental builds, but those can be added on top.

**Comment by robwierzbowski** [comment]
Released 1.0.0-alpha.3. With the caveats in the readme I think it's ok to release. I just want to test the error handling based on some posted issues first.

**Comment by sindresorhus** [comment]
@robwierzbowski Ready for merge?

**Comment by kevva** [comment]
@robwierzbowski, ping.

**Comment by robwierzbowski** [comment]
Just getting back from being in Barcelona for three weeks. This is ready to
go with a little documentation on error handling. We can add requested
features iteratively afterward.

On Monday, March 9, 2015, Kevin Mårtensson <notifications@github.com> wrote:

> @robwierzbowski <https://github.com/robwierzbowski>, ping.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/pull/137#issuecomment-77910880>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
OK, that's it. Ready to make 1.0 real and go from there.

**Comment by robwierzbowski** [comment]
Published 1.0.0. OK, now to take care of these: https://github.com/sindresorhus/gulp-ruby-sass#important

**Comment by sindresorhus** [comment]
Woot! Awesome work @robwierzbowski :)

5fa79994-b5ee-11e3-9a4d-b19557d7480b

**Comment by fbm-static** [comment]
ahaha

**Pull request merged**
