### PR TITLE
Array sources

### PR DESCRIPTION
**Pull request by robwierzbowski**
This PR brings gulp-ruby-sass's source adapter closer to `gulp.src` by implementing `['array**/*', 'sources/*']`. 

This now works exactly like `gulp.src`. Collisions that would occur if you tried to compile `['app/styles.scss', 'documentation/styles.scss']` are handled by a `base` option (once again, just like `gulp.src`). Removing the ability to compile directories makes this trivial, and works more like what people are used to with gulp. 

**Definitely breaking changes.** I'm going to fix caching in another PR then merge and release 2.0 simultaneously.

### CODE REVIEW

**Comment by robwierzbowski** [comment]
@sindresorhus, can I get your opinion on this?

When compiling array sources like `['source/app/styles.scss', 'source/documentation/styles.scss']`, I've coded up some methods that figure out the shared base directory (in this case `source`). The resulting files piped to `gulp.dest` are `app/styles.css` and `documentation/styles.css`. 

`gulp.src` handles this a little different. It will push the two files named `styles.css` through the stream and overwrite one when output to `gulp.dest`. A user sets the `base` option to `source` to make it work correctly.

What do you think? Should I refactor my code to work exactly like `gulp.src`, or is this difference preferable? I'm leaning towards the latter, but thought I would ask for a second opinion.

**Comment by sindresorhus** [comment]
I prefer the `gulp.src` way.

**Comment by robwierzbowski** [comment]
Me too, I wish I had understood exactly how it worked before I coded this up :sob: :+1:

**Comment by robwierzbowski** [comment]
Thanks.

**Pull request merged**
